
name: Deploy to Test server

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "${{ secrets.PIXI_USERNAME }}"
          host: "${{ secrets.PIXI_IP }}"
          password: "${{ secrets.PIXIE_PASS }}"
          port: 21098
          script: 'cd /home/${{ secrets.PIXI_USERNAME }}/www && ./server_deploy.sh'
